import { Hono } from "hono";
import type { Env } from "@/env";
import { withPublicCache } from "@/http/cache";
import { listEnabledModelAliases, listPublicGatewayRows } from "@/repositories/gateway";

const CACHE = { edgeTtlSeconds: 5 * 60, staleWhileRevalidateSeconds: 5 * 60, cacheTags: ["web-api-gateway-models"] } as const;
export const publicGatewayRouter = new Hono<{ Bindings: Env }>();

async function gatewayModels(env: Env) {
	const rows = await listPublicGatewayRows(env); const now = Date.now(); const grouped = new Map<string, Record<string, any>>();
	for (const row of rows) { const key = `${row.providerId}:${row.apiModelId}`; const from = row.effectiveFrom ? Date.parse(row.effectiveFrom) : Number.NEGATIVE_INFINITY; const to = row.effectiveTo ? Date.parse(row.effectiveTo) : Number.POSITIVE_INFINITY; const retirement = row.retirementDate ? Date.parse(row.retirementDate) : Number.POSITIVE_INFINITY; const current = grouped.get(key) ?? { modelId: row.apiModelId, internalModelId: row.modelId, selectorModelId: row.modelId || row.apiModelId, providerId: row.providerId, capabilities: [], capabilityParamsById: {}, effectiveFrom: row.effectiveFrom, effectiveTo: row.effectiveTo, providerName: row.providerName, providerFamilyId: row.providerFamilyId, providerOfferLabel: row.providerOfferLabel, providerOfferScope: row.providerOfferScope, providerPromptTrainingPolicy: row.providerPromptTrainingPolicy, modelName: row.modelName, modelStatus: row.modelStatus, organisationId: row.organisationId, organisationName: row.organisationName, previousModelId: row.previousModelId, releaseDate: row.releaseDate, announcementDate: row.announcementDate, isAvailable: row.routingEnabled && now >= from && now < to && now < retirement && row.modelStatus.toLowerCase() !== "retired" }; current.capabilities.push(row.capabilityId); current.capabilityParamsById[row.capabilityId] = row.capabilityParams ?? {}; grouped.set(key, current); }
	const output: Array<Record<string, any>> = [...grouped.values()].map((row) => ({ ...row, capabilities: [...new Set(row.capabilities as string[])].sort((a, b) => a.localeCompare(b, "en")) }));
	return output.sort((a, b) => String(a.providerId).localeCompare(String(b.providerId)) || String(a.modelId).localeCompare(String(b.modelId)));
}

publicGatewayRouter.get("/gateway/models", async (c) => { try { const models = await gatewayModels(c.env); const availableOnly = c.req.query("available_only") !== "false"; return withPublicCache(c.json({ models: availableOnly ? models.filter((model) => model.isAvailable) : models }), CACHE); } catch (error) { console.error("[web-api/gateway] models failed", error); return c.json({ error: "gateway_models_unavailable" }, 503); } });

publicGatewayRouter.get("/gateway/model-aliases", async (c) => { try { const [models, aliasRows] = await Promise.all([gatewayModels(c.env), listEnabledModelAliases(c.env)]); const byId = new Map<string, Record<string, unknown>[]>(); for (const model of models.filter((row) => row.isAvailable)) for (const id of [model.modelId, model.selectorModelId, model.internalModelId]) if (id) byId.set(String(id), [...(byId.get(String(id)) ?? []), model]); const aliases: Array<Record<string, unknown>> = []; const seen = new Set<string>(); for (const row of aliasRows) { const slug = row.aliasSlug.trim(); const [resolved] = byId.get(row.modelSlug) ?? []; if (!slug || !resolved || seen.has(slug)) continue; seen.add(slug); aliases.push({ ...resolved, modelId: slug, selectorModelId: slug, modelName: slug.split(/[\/_-]+/).filter(Boolean).map((part) => part.slice(0, 1).toUpperCase() + part.slice(1)).join(" ") }); } return withPublicCache(c.json({ aliases }), CACHE); } catch (error) { console.error("[web-api/gateway] aliases failed", error); return c.json({ error: "gateway_aliases_unavailable" }, 503); } });
