import { Hono } from "hono";
import type { Env } from "@/env";
import { withPublicCache, type PublicCachePolicy } from "@/http/cache";
import { fetchModelsPageCatalogue } from "@/models/page-catalogue";
import { findReferenceProvider, getReferenceBenchmark, getReferenceFamily, getReferencePlan, labOrganisation, listReferenceBenchmarks, listReferenceFamilies, listReferenceLabs, listReferencePlans, listReferenceProviders } from "@/repositories/reference-data";

const REFERENCE_CACHE: PublicCachePolicy = { edgeTtlSeconds: 86400, staleWhileRevalidateSeconds: 604800, cacheTags: ["web-api-reference-data"] };
const policy = (tag: string): PublicCachePolicy => ({ ...REFERENCE_CACHE, cacheTags: ["web-api-reference-data", tag] });
export const publicReferenceDataRouter = new Hono<{ Bindings: Env }>();
const notFound = (c: { json: (value: unknown, status: number) => Response }, resource: string) => c.json({ error: `${resource}_not_found` }, 404);
const countryName = (iso: string) => { try { return new Intl.DisplayNames(["en"], { type: "region" }).of(iso) ?? iso; } catch { return iso; } };

async function countrySummaries(env: Env) {
	const [labs, catalogue] = await Promise.all([listReferenceLabs(env), fetchModelsPageCatalogue(env, {}, "v2")]); const modelsByLab = new Map<string, Array<Record<string, unknown>>>();
	for (const model of catalogue.models) { const id = String(model.organisation_id ?? ""); if (id) modelsByLab.set(id, [...(modelsByLab.get(id) ?? []), model]); }
	const countries = new Map<string, Array<Record<string, unknown>>>();
	for (const lab of labs) { const iso = lab.countryCode.trim().toUpperCase(); if (!iso) continue; const organisation = labOrganisation(lab), models = [...(modelsByLab.get(lab.labSlug) ?? [])].sort((a, b) => Number(b.primary_timestamp ?? 0) - Number(a.primary_timestamp ?? 0)).map((model) => ({ ...model, organisation_id: lab.labSlug, organisation_name: lab.name, organisation_colour: organisation.colour, organisation: { name: lab.name, colour: organisation.colour } })); countries.set(iso, [...(countries.get(iso) ?? []), { organisation_id: lab.labSlug, organisation_name: lab.name, colour: organisation.colour, models, modelCount: models.length, latestModel: models[0] ?? null }]); }
	return [...countries].map(([iso, organisations]) => { const sorted = organisations.sort((a, b) => Number(b.modelCount) - Number(a.modelCount)), models = sorted.flatMap((row) => row.models as Array<Record<string, unknown>>).sort((a, b) => Number(b.primary_timestamp ?? 0) - Number(a.primary_timestamp ?? 0)); return { iso, countryName: countryName(iso), totalOrganisations: sorted.length, totalModels: models.length, recentModels: models.slice(0, 4), latestModel: models[0] ?? null, organisations: sorted }; }).sort((a, b) => b.totalModels - a.totalModels);
}

publicReferenceDataRouter.get("/organisations", async (c) => { try { const organisations = (await listReferenceLabs(c.env)).map((lab) => { const row = labOrganisation(lab); return { organisation_id: row.organisation_id, organisation_name: row.name, country_code: row.country_code, colour: row.colour }; }); return withPublicCache(c.json({ organisations }), policy("web-api-organisations")); } catch (error) { console.error("[web-api/reference] organisations failed", error); return c.json({ error: "organisations_unavailable" }, 503); } });
publicReferenceDataRouter.get("/benchmarks", async (c) => { try { return withPublicCache(c.json({ benchmarks: await listReferenceBenchmarks(c.env, c.req.query("sort") === "coverage") }), policy("web-api-benchmarks")); } catch (error) { console.error("[web-api/reference] benchmarks failed", error); return c.json({ error: "benchmarks_unavailable" }, 503); } });
publicReferenceDataRouter.get("/benchmarks/:benchmarkId", async (c) => { const id = c.req.param("benchmarkId"); try { const benchmark = await getReferenceBenchmark(c.env, id); return benchmark ? withPublicCache(c.json({ benchmark }), policy(`web-api-benchmark-${encodeURIComponent(id).replace(/%/g, "")}`)) : notFound(c, "benchmark"); } catch (error) { console.error("[web-api/reference] benchmark failed", { id, error }); return c.json({ error: "benchmark_unavailable" }, 503); } });
publicReferenceDataRouter.get("/api-providers/:providerId/header", async (c) => { const id = c.req.param("providerId").trim(); if (["inception", "inceptron", "nextbit"].includes(id.toLowerCase())) return notFound(c, "api_provider"); try { const row = await findReferenceProvider(c.env, id); return row ? withPublicCache(c.json({ provider: { api_provider_id: row.providerSlug, api_provider_name: row.name, country_code: row.countryCode } }), policy(`web-api-provider-${encodeURIComponent(id).replace(/%/g, "")}`)) : notFound(c, "api_provider"); } catch (error) { console.error("[web-api/reference] provider failed", error); return c.json({ error: "provider_unavailable" }, 503); } });
publicReferenceDataRouter.get("/sources", async (c) => { try { const sources = (await listReferenceProviders(c.env)).map((row) => ({ api_provider_id: row.providerSlug, api_provider_name: row.name, country_code: row.countryCode })); return withPublicCache(c.json({ sources }), policy("web-api-sources")); } catch (error) { console.error("[web-api/reference] sources failed", error); return c.json({ error: "sources_unavailable" }, 503); } });
publicReferenceDataRouter.get("/families", async (c) => { try { return withPublicCache(c.json({ families: await listReferenceFamilies(c.env) }), policy("web-api-families")); } catch (error) { console.error("[web-api/reference] families failed", error); return c.json({ error: "families_unavailable" }, 503); } });
publicReferenceDataRouter.get("/families/:familyId", async (c) => { const id = c.req.param("familyId"); try { const family = await getReferenceFamily(c.env, id); return family ? withPublicCache(c.json(family), policy(`web-api-family-${encodeURIComponent(id).replace(/%/g, "")}`)) : notFound(c, "family"); } catch (error) { console.error("[web-api/reference] family failed", error); return c.json({ error: "family_unavailable" }, 503); } });
publicReferenceDataRouter.get("/subscription-plans", async (c) => { try { return withPublicCache(c.json({ subscription_plans: await listReferencePlans(c.env) }), policy("web-api-subscription-plans")); } catch (error) { console.error("[web-api/reference] plans failed", error); return c.json({ error: "subscription_plans_unavailable" }, 503); } });
publicReferenceDataRouter.get("/subscription-plans/:planId", async (c) => { const id = c.req.param("planId"); try { const plan = await getReferencePlan(c.env, id); return plan ? withPublicCache(c.json({ subscription_plan: plan }), policy(`web-api-subscription-plan-${encodeURIComponent(id).replace(/%/g, "")}`)) : notFound(c, "subscription_plan"); } catch (error) { console.error("[web-api/reference] plan failed", error); return c.json({ error: "subscription_plan_unavailable" }, 503); } });
publicReferenceDataRouter.get("/countries", async (c) => { try { const countries = (await countrySummaries(c.env)).map(({ iso, countryName, totalOrganisations, totalModels }) => ({ iso, countryName, totalOrganisations, totalModels })); return withPublicCache(c.json({ countries }), policy("web-api-countries")); } catch (error) { console.error("[web-api/reference] countries failed", error); return c.json({ error: "countries_unavailable" }, 503); } });
publicReferenceDataRouter.get("/countries/:iso", async (c) => { const iso = c.req.param("iso").trim().toUpperCase(); try { const country = (await countrySummaries(c.env)).find((entry) => entry.iso === iso); return country ? withPublicCache(c.json({ country }), policy(`web-api-country-${iso}`)) : notFound(c, "country"); } catch (error) { console.error("[web-api/reference] country failed", error); return c.json({ error: "country_unavailable" }, 503); } });
