export type ModelPerformancePoint = { bucket: string; avgThroughput: number | null; avgOutputSpeed?: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; avgPhaseoOverheadMs?: number | null; avgTpotMs?: number | null; avgItlMs?: number | null; requests: number; successPct: number | null };
export type ModelSuccessPoint = { bucket: string; overallSuccessPct: number | null; worstProviderSuccessPct: number | null; providerCount?: number; requests: number };
export type ModelTimeOfDayPoint = { hour: number; avgThroughput: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; sampleCount: number };
export type ModelProviderUptimeBucket = { start: string; end: string; successPct: number | null };
export type ModelProviderPerformance = { provider: string; providerName: string; providerColor?: string | null; avgThroughput: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; requests: number; uptimePct: number | null; uptimeBuckets: ModelProviderUptimeBucket[] };
export type ModelProviderDailyPoint = { day: string; provider: string; providerName: string; providerColor: string | null; avgThroughput: number | null; avgOutputSpeed?: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; avgPhaseoOverheadMs?: number | null; avgTpotMs?: number | null; avgItlMs?: number | null; requests: number };
export type ModelProviderPercentileDailyPoint = ModelProviderDailyPoint & { percentile: number };
export type ModelPerformanceQualityPoint = { bucket: string; toolCallSuccessPct: number | null; structuredOutputSuccessPct: number | null; cacheHitRatePct: number | null; requests: number };
export interface ModelPerformanceSummary { avgThroughput: number | null; avgOutputSpeed?: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; avgPhaseoOverheadMs?: number | null; avgTpotMs?: number | null; avgItlMs?: number | null; uptimePct: number | null; totalRequests: number; successfulRequests: number }
export interface ModelPerformanceRange { start: string; end: string }
export interface ModelPerformanceMetrics { cloudflareColo?: string | null; percentile?: number | null; streamMode?: "all" | "stream" | "non_stream"; contextBucket?: "all" | "lte_4k" | "4k_16k" | "16k_64k" | "gt_64k"; summary: ModelPerformanceSummary; prevSummary?: ModelPerformanceSummary | null; hourly: ModelPerformancePoint[]; successSeries: ModelSuccessPoint[]; timeOfDay: ModelTimeOfDayPoint[]; providerPerformance: ModelProviderPerformance[]; providerDaily7d: ModelProviderDailyPoint[]; providerPercentileDaily7d?: ModelProviderPercentileDailyPoint[]; qualitySeries?: ModelPerformanceQualityPoint[]; dataRange: ModelPerformanceRange; cumulativeTokens?: number | null; releaseDate?: string | null }
export interface ModelPerformanceActivitySnapshot { summary: ModelPerformanceSummary; providerPerformance: ModelProviderPerformance[]; cumulativeTokens?: number | null }
