import { gatewayRequests, v2Providers, v2RequestFacts } from "@phaseo/db/schema";
import { sql } from "@phaseo/db/query";

import { createDatabase } from "@/data/db";
import type { Env } from "@/env";

export async function getModelPerformanceBundle(env: Env, input: { modelSlug: string; cloudflareColo: string | null; streamMode: string; percentile: number }) {
	const { db, client } = createDatabase(env); const stream = input.streamMode === "stream" ? true : input.streamMode === "non_stream" ? false : null;
	try { const [row] = await db.execute<Record<string, any>>(sql`
		with base as (
			select request.*, fact.cloudflare_colo
			from ${gatewayRequests} request
			left join ${v2RequestFacts} fact
				on fact.gateway_request_id=request.id
				and fact.gateway_request_created_at=request.created_at
			where coalesce(nullif(request.canonical_model_id,''),request.model_id)=${input.modelSlug}
				and request.created_at>=now()-interval '7 days'
				and (${input.cloudflareColo}::text is null or upper(fact.cloudflare_colo)=${input.cloudflareColo})
				and (${stream}::boolean is null or request.stream=${stream})
		),
		last24 as (select jsonb_build_object('avg_throughput',percentile_cont(${input.percentile}) within group(order by throughput) filter(where throughput>0),'avg_latency_ms',percentile_cont(${input.percentile}) within group(order by latency_ms) filter(where latency_ms>0),'avg_generation_ms',percentile_cont(${input.percentile}) within group(order by generation_ms) filter(where generation_ms>0),'uptime_pct',case when count(*)>0 then count(*) filter(where success)*100.0/count(*) end,'total_requests',count(*),'successful_requests',count(*) filter(where success)) value from base where created_at>=now()-interval '24 hours'),
		hourly as (select coalesce(jsonb_agg(value order by bucket),'[]') value from (select date_trunc('hour',created_at) bucket,jsonb_build_object('bucket',date_trunc('hour',created_at),'avg_throughput',avg(throughput),'avg_latency_ms',avg(latency_ms),'avg_generation_ms',avg(generation_ms),'requests',count(*),'success_pct',count(*) filter(where success)*100.0/count(*)) value from base where created_at>=now()-interval '24 hours' group by 1) x),
		provider24 as (select coalesce(jsonb_agg(value),'[]') value from (select provider,jsonb_build_object('provider',provider,'provider_name',max(p.name),'requests',count(*),'uptime_pct',count(*) filter(where success)*100.0/count(*),'avg_latency_ms',avg(latency_ms),'avg_generation_ms',avg(generation_ms),'avg_throughput',avg(throughput)) value from base left join ${v2Providers} p on p.provider_slug=base.provider where created_at>=now()-interval '24 hours' and provider is not null group by provider) x),
		daily as (select coalesce(jsonb_agg(value order by day),'[]') value from (select date_trunc('day',created_at) day,provider,jsonb_build_object('day',date_trunc('day',created_at),'provider',provider,'provider_name',max(p.name),'requests',count(*),'avg_latency_ms',avg(latency_ms),'avg_generation_ms',avg(generation_ms),'avg_throughput',avg(throughput)) value from base left join ${v2Providers} p on p.provider_slug=base.provider where provider is not null group by 1,provider) x),
		cache_hourly as (select coalesce(jsonb_agg(jsonb_build_object('bucket',bucket,'cached_input_pct',case when input_tokens>0 then cached_tokens*100.0/input_tokens end,'telemetry_requests',requests) order by bucket),'[]') value from (select date_trunc('hour',created_at) bucket,sum(coalesce(usage_cached_read_tokens,0)) cached_tokens,sum(coalesce(usage_input_tokens,0)) input_tokens,count(*) requests from base where created_at>=now()-interval '24 hours' group by 1)x),
		cache_daily as (select coalesce(jsonb_agg(jsonb_build_object('day',day,'provider',provider,'cached_input_pct',case when input_tokens>0 then cached_tokens*100.0/input_tokens end,'cached_input_tokens',cached_tokens,'effective_input_tokens',input_tokens,'telemetry_requests',requests) order by day),'[]') value from (select date_trunc('day',created_at) day,provider,sum(coalesce(usage_cached_read_tokens,0)) cached_tokens,sum(coalesce(usage_input_tokens,0)) input_tokens,count(*) requests from base where provider is not null group by 1,provider)x)
		select jsonb_build_object('last_24h',last24.value,'hourly_24h',hourly.value,'provider_uptime_24h',provider24.value,'provider_daily_7d',daily.value,'time_of_day_5d','[]'::jsonb,'quality_series','[]'::jsonb) performance,jsonb_build_object('hourly_24h',cache_hourly.value,'provider_daily_7d',cache_daily.value) cached_input from last24,hourly,provider24,daily,cache_hourly,cache_daily
	`); const performance=row?.performance??null; const health=(performance?.provider_uptime_24h??[]).map((value:Record<string,unknown>)=>({provider_id:value.provider,provider_name:value.provider_name,health_requests:value.requests,uptime_pct:value.uptime_pct,percentile_latency_ms:value.avg_latency_ms,percentile_throughput:value.avg_throughput,buckets:[]})); return { performance, health, cachedInput:row?.cached_input??{}, percentileSeries:[] as Record<string,unknown>[] }; } finally { await client.end({timeout:1}); }
}

export async function getModelProviderHealthRows(env: Env, modelSlug: string, windowDays: number, percentile: number) { const {db,client}=createDatabase(env); try { const rows=await db.execute<Record<string,unknown>>(sql`select request.provider provider_id,max(provider.name) provider_name,count(*)::bigint requests,count(*)::bigint health_requests,count(*) filter(where request.success)::bigint health_success_requests,count(*) filter(where request.success)*100.0/nullif(count(*),0) uptime_pct,percentile_cont(${percentile}) within group(order by request.latency_ms) filter(where request.latency_ms>0) percentile_latency_ms,percentile_cont(${percentile}) within group(order by request.throughput) filter(where request.throughput>0) percentile_throughput from ${gatewayRequests} request left join ${v2Providers} provider on provider.provider_slug=request.provider where coalesce(nullif(request.canonical_model_id,''),request.model_id)=${modelSlug} and request.created_at>=now()-(${windowDays}*interval '1 day') and request.provider is not null group by request.provider order by requests desc`); return [...rows]; } finally {await client.end({timeout:1});} }
