import { v2BenchmarkResults, v2Benchmarks, v2Labs, v2ModelFamilies, v2Models, v2Providers, v2SubscriptionPlanFeatures, v2SubscriptionPlanModels, v2SubscriptionPlans } from "@phaseo/db/schema";
import { and, asc, desc, eq, inArray } from "@phaseo/db/query";

import { createDatabase } from "@/data/db";
import type { Env } from "@/env";

const meta = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export const labOrganisation = (lab: typeof v2Labs.$inferSelect) => { const details = meta(lab.metadata); return { organisation_id: lab.labSlug, name: lab.name, country_code: lab.countryCode, colour: details.colour ?? null, display_name: details.display_name ?? lab.name, logo: details.logo ?? null, logo_url: details.logo_url ?? null }; };

export async function listReferenceLabs(env: Env) { const { db, client } = createDatabase(env); try { return await db.select().from(v2Labs).orderBy(asc(v2Labs.name)); } finally { await client.end({ timeout: 1 }); } }
export async function listReferenceBenchmarks(env: Env, coverage: boolean) { const { db, client } = createDatabase(env); try { const rows = await db.select().from(v2Benchmarks).orderBy(coverage ? desc(v2Benchmarks.totalModels) : asc(v2Benchmarks.name), asc(v2Benchmarks.name)); return rows.map((row) => ({ benchmark_id: row.benchmarkId, benchmark_name: row.name, total_models: row.totalModels ?? 0 })); } finally { await client.end({ timeout: 1 }); } }
export async function findReferenceProvider(env: Env, id: string) { const { db, client } = createDatabase(env); try { const [row] = await db.select().from(v2Providers).where(eq(v2Providers.providerSlug, id)).limit(1); return row ?? null; } finally { await client.end({ timeout: 1 }); } }
export async function listReferenceProviders(env: Env) { const { db, client } = createDatabase(env); try { return await db.select().from(v2Providers).orderBy(asc(v2Providers.name)); } finally { await client.end({ timeout: 1 }); } }

export async function getReferenceBenchmark(env: Env, benchmarkId: string) {
	const { db, client } = createDatabase(env); try {
		const [[benchmark], results] = await Promise.all([db.select().from(v2Benchmarks).where(eq(v2Benchmarks.benchmarkId, benchmarkId)).limit(1), db.select({ result: v2BenchmarkResults, model: v2Models, lab: v2Labs }).from(v2BenchmarkResults).innerJoin(v2Models, and(eq(v2Models.modelSlug, v2BenchmarkResults.modelSlug), eq(v2Models.hidden, false))).innerJoin(v2Labs, eq(v2Labs.labSlug, v2Models.labSlug)).where(eq(v2BenchmarkResults.benchmarkId, benchmarkId)).orderBy(asc(v2BenchmarkResults.rank))]);
		if (!benchmark) return null; return { id: benchmark.benchmarkId, name: benchmark.name, category: benchmark.category, ascending_order: benchmark.ascendingOrder, total_models: benchmark.totalModels, link: benchmark.link, type: benchmark.benchmarkType, results: results.map(({ result, model, lab }) => ({ id: result.resultId, model_id: result.modelSlug, score: result.score, is_self_reported: result.isSelfReported, other_info: result.otherInfo, source_link: result.sourceLink, created_at: result.createdAt, updated_at: result.updatedAt, rank: result.rank, model: { model_id: model.modelSlug, name: model.name, release_date: model.releasedAt, announcement_date: model.announcedAt, organisation: labOrganisation(lab) } })) };
	} finally { await client.end({ timeout: 1 }); }
}

export async function listReferenceFamilies(env: Env) { const { db, client } = createDatabase(env); try { const rows = await db.select({ family: v2ModelFamilies, lab: v2Labs }).from(v2ModelFamilies).innerJoin(v2Labs, eq(v2Labs.labSlug, v2ModelFamilies.labSlug)).orderBy(desc(v2ModelFamilies.createdAt)); return rows.map(({ family, lab }) => ({ family_id: family.familySlug, family_name: family.name, organisation_id: family.labSlug, organisation_name: lab.name, created_at: family.createdAt })); } finally { await client.end({ timeout: 1 }); } }
export async function getReferenceFamily(env: Env, familyId: string) { const { db, client } = createDatabase(env); try { const [[family], models] = await Promise.all([db.select().from(v2ModelFamilies).where(eq(v2ModelFamilies.familySlug, familyId)).limit(1), db.select({ model: v2Models, lab: v2Labs }).from(v2Models).innerJoin(v2Labs, eq(v2Labs.labSlug, v2Models.labSlug)).where(and(eq(v2Models.familySlug, familyId), eq(v2Models.hidden, false))).orderBy(desc(v2Models.releasedAt))]); if (!family) return null; return { family_id: family.familySlug, family_name: family.name, models: models.map(({ model, lab }) => ({ model_id: model.modelSlug, name: model.name, organisation_id: model.labSlug, status: model.status, release_date: model.releasedAt, announcement_date: model.announcedAt, organisation: labOrganisation(lab) })) }; } finally { await client.end({ timeout: 1 }); } }

export async function listReferencePlans(env: Env) { const { db, client } = createDatabase(env); try { const rows = await db.select({ plan: v2SubscriptionPlans, lab: v2Labs }).from(v2SubscriptionPlans).leftJoin(v2Labs, eq(v2Labs.labSlug, v2SubscriptionPlans.labSlug)).orderBy(asc(v2SubscriptionPlans.name)); const grouped = new Map<string, Record<string, unknown>>(); for (const { plan, lab } of rows) { const value = grouped.get(plan.planId) ?? { plan_uuid: plan.planUuid, plan_id: plan.planId, name: plan.name, organisation_id: plan.labSlug, description: plan.description, link: plan.link, other_info: plan.otherInfo, organisation: lab ? labOrganisation(lab) : null, prices: [] }; (value.prices as Array<Record<string, unknown>>).push({ frequency: plan.frequency, price: plan.price, currency: plan.currency, plan_uuid: plan.planUuid }); grouped.set(plan.planId, value); } return [...grouped.values()].filter((plan) => (plan.prices as unknown[]).length); } finally { await client.end({ timeout: 1 }); } }

export async function getReferencePlan(env: Env, planId: string) { const { db, client } = createDatabase(env); try { const planRows = await db.select({ plan: v2SubscriptionPlans, lab: v2Labs }).from(v2SubscriptionPlans).leftJoin(v2Labs, eq(v2Labs.labSlug, v2SubscriptionPlans.labSlug)).where(eq(v2SubscriptionPlans.planId, planId)); if (!planRows.length) return null; const primary = planRows[0]; const [features, links] = await Promise.all([db.select().from(v2SubscriptionPlanFeatures).where(eq(v2SubscriptionPlanFeatures.planUuid, primary.plan.planUuid)).orderBy(asc(v2SubscriptionPlanFeatures.featureName)), db.select({ link: v2SubscriptionPlanModels, model: v2Models, lab: v2Labs }).from(v2SubscriptionPlanModels).innerJoin(v2Models, and(eq(v2Models.modelSlug, v2SubscriptionPlanModels.modelSlug), eq(v2Models.hidden, false))).innerJoin(v2Labs, eq(v2Labs.labSlug, v2Models.labSlug)).where(eq(v2SubscriptionPlanModels.planUuid, primary.plan.planUuid)).orderBy(asc(v2Models.modelSlug))]); const { plan, lab } = primary; return { plan_uuid: plan.planUuid, plan_id: plan.planId, name: plan.name, organisation_id: plan.labSlug, description: plan.description, link: plan.link, other_info: plan.otherInfo, organisation: lab ? labOrganisation(lab) : null, features: features.map((row) => ({ feature_name: row.featureName, feature_value: row.featureValue, feature_description: row.featureDescription, other_info: row.otherInfo })), models: links.map(({ link, model, lab: modelLab }) => ({ model_id: link.modelSlug, model_info: link.modelInfo, rate_limit: link.rateLimit, other_info: link.otherInfo, model: { model_id: model.modelSlug, name: model.name, organisation_id: model.labSlug, organisation_name: modelLab.name } })), prices: planRows.map(({ plan: row }) => ({ price: row.price, currency: row.currency, frequency: row.frequency, plan_uuid: row.planUuid })) }; } finally { await client.end({ timeout: 1 }); } }
